# Generated by Django 5.1.5 on 2025-01-28 18:34

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='steps',
            field=tinymce.models.HTMLField(),
        ),
    ]
