# Generated by Django 5.1.5 on 2025-01-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_solution_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='description',
            field=models.TextField(),
        ),
    ]
