# Generated by Django 5.1.5 on 2025-02-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_case_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
